package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Implements the DataReader interface to read patient health data from local files.
 * <p>
 * This class scans a specified directory for output files generated by the simulator,
 * parses the text-based data records, and stores them securely in the DataStorage instance.
 */
public class FileDataReader implements DataReader {
    private String outputDirectory;

    /**
     * Constructs a new FileDataReader with the target directory path.
     *
     * @param outputDirectory the path to the directory containing simulated data files
     */
    public FileDataReader(String outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    /**
     * Reads data from all files within the specified directory and loads them into storage.
     *
     * @param dataStorage the centralized storage where parsed patient data will be stored
     * @throws IOException if there is an error reading the files or directory
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File folder = new File(outputDirectory);
        File[] listOfFiles = folder.listFiles();

        if (listOfFiles == null) {
            return; // No files found or directory is invalid
        }

        for (File file : listOfFiles) {
            if (file.isFile()) {
                try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        try {
                            // Parse standard comma-separated output format
                            String[] parts = line.split(",");
                            if (parts.length == 4) {
                                int patientId = Integer.parseInt(parts[0].split(":")[1].trim());
                                long timestamp = Long.parseLong(parts[1].split(":")[1].trim());
                                String label = parts[2].split(":")[1].trim();
                                double data = Double.parseDouble(parts[3].split(":")[1].trim());
                                
                                dataStorage.addPatientData(patientId, data, label, timestamp);
                            }
                        } catch (Exception e) {
                            // Silently skip malformed lines to prevent simulation crash
                        }
                    }
                }
            }
        }
    }
}